[package]
name = "temp"
version = "0.1.0"
edition = "2021"

[dependencies]
dbsp = { git = "https://github.com/vmware/database-stream-processor.git" }
# The following is used while I have outstanding PRs not yet merged
# dbsp = { path = "/home/mbudiu/git/database-stream-processor" }

tuple = { path = "../lib/tuple" }
sqllibbool = { path = "../lib/sqllibbool" }
sqlvalue = { path = "../lib/sqlvalue" }
ordered-float = { version = "2.0.0" }
serde = { version = "1.0", features = ["derive"] }
hashing = { path = "../lib/hashing" }
